/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_host_ipt_iha_IhaManagerJni */

#ifndef _Included_com_intel_host_ipt_iha_IhaManagerJni
#define _Included_com_intel_host_ipt_iha_IhaManagerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAInit
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHADeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHADeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAStartProvisioning
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAStartProvisioning
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAEndProvisioning
 * Signature: (Ljava/lang/String;I[S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAEndProvisioning
  (JNIEnv *, jclass, jstring, jint, jshortArray);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHASendData
 * Signature: (Ljava/lang/String;IS[B)V
 */
JNIEXPORT void JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHASendData
  (JNIEnv *, jclass, jstring, jint, jshort, jbyteArray);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAReceiveData
 * Signature: (Ljava/lang/String;IS[S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAReceiveData
  (JNIEnv *, jclass, jstring, jint, jshort, jshortArray);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAProcessSVPMessage
 * Signature: (Ljava/lang/String;I[B)V
 */
JNIEXPORT void JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAProcessSVPMessage
  (JNIEnv *, jclass, jstring, jint, jbyteArray);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAGetSVPMessage
 * Signature: (Ljava/lang/String;I[S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAGetSVPMessage
  (JNIEnv *, jclass, jstring, jint, jshortArray);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHASendAndReceiveData
 * Signature: (Ljava/lang/String;IS[B[S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHASendAndReceiveData
  (JNIEnv *, jclass, jstring, jint, jshort, jbyteArray, jshortArray);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAGetCapabilities
 * Signature: (Ljava/lang/String;S[S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAGetCapabilities
  (JNIEnv *, jclass, jstring, jshort, jshortArray);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAGetVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAInstall
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAInstall
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAUninstall
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAUninstall
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHADoFWUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHADoFWUpdate
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAGetOTP
 * Signature: (Ljava/lang/String;I[B[B[S[S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAGetOTP
  (JNIEnv *, jclass, jstring, jint, jbyteArray, jbyteArray, jshortArray, jshortArray);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAGetOTPSStatus
 * Signature: (Ljava/lang/String;IS)I
 */
JNIEXPORT jint JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAGetOTPSStatus
  (JNIEnv *, jclass, jstring, jint, jshort);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAGetOTPCapabilities
 * Signature: (Ljava/lang/String;S[S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAGetOTPCapabilities
  (JNIEnv *, jclass, jstring, jshort, jshortArray);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAInstallOTPS
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAInstallOTPS
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAUninstallOTPS
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAUninstallOTPS
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHAUnregisterEventCb
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHAUnregisterEventCb
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_intel_host_ipt_iha_IhaManagerJni
 * Method:    IHA_GetAppInstId
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_host_ipt_iha_IhaManagerJni_IHA_1GetAppInstId
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
